DOCK_PRIORITY = [16, 17, 18]

AISLES = [
    {
        "id": "S16-2",
        "docks": [18],
        "capacityUnits": 16,
        "maxStores": 2,
        "x": 58.5,
        "y": 15.8,
        "width": 21,
        "height": 3,
        "priority": 1,
    },
    {
        "id": "S16-6",
        "docks": [17, 18],
        "capacityUnits": 16,
        "maxStores": 2,
        "x": 58.5,
        "y": 20.1,
        "width": 21,
        "height": 3,
        "priority": 2,
    },
    {
        "id": "S16-7",
        "docks": [17],
        "capacityUnits": 16,
        "maxStores": 2,
        "x": 58.5,
        "y": 24.4,
        "width": 21,
        "height": 3,
        "priority": 3,
    },
    {
        "id": "S16-8",
        "docks": [16, 17],
        "capacityUnits": 16,
        "maxStores": 2,
        "x": 58.5,
        "y": 28.7,
        "width": 21,
        "height": 3,
        "priority": 4,
    },
    {
        "id": "S16-9",
        "docks": [16, 17],
        "capacityUnits": 16,
        "maxStores": 2,
        "x": 58.5,
        "y": 33,
        "width": 21,
        "height": 3,
        "priority": 5,
    },
    {
        "id": "S17-8",
        "docks": [16],
        "capacityUnits": 16,
        "maxStores": 2,
        "x": 58.5,
        "y": 40.2,
        "width": 21,
        "height": 3,
        "priority": 6,
    },
    {
        "id": "S17-9",
        "docks": [16],
        "capacityUnits": 16,
        "maxStores": 2,
        "x": 58.5,
        "y": 44.5,
        "width": 21,
        "height": 3,
        "priority": 7,
    },
    {
        "id": "S17-10",
        "docks": [16],
        "capacityUnits": 16,
        "maxStores": 2,
        "x": 58.5,
        "y": 48.8,
        "width": 21,
        "height": 3,
        "priority": 8,
    },
]
